### ISSUE TITLE
Can't install it 

### ISSUE THREAD

**Issue by MarieSoukaina** [sham00n/buster#1]
Can't install it on Kali Linux  ... 
Error : x86_64-linux-gnu-gcc : error: src/gevent/_greenlet_primitives.C : Can't find file or directory.

**Comment by sham00n** [comment]
i developed this project on kali and tested it on a fresh version,can u try `pip3 install gevent ` ?

**Comment by NTgitdude23** [comment]
Same here, but mine is also giving me this error but many times....x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.

**Comment by sham00n** [comment]
try `sudo pip3 install cython`

**Comment by MarieSoukaina** [comment]
Okay, it might work now.
I tryed what you said, then I tried to install buster again, test it but I needed to install aiohttp_socks don't know why and now it's working ! 
Thanks for yout help :)
