### ISSUE TITLE
Unable to install Buster

### ISSUE THREAD

**Issue by OSINT007** [sham00n/buster#2]
![Picture1](https://user-images.githubusercontent.com/53490321/62151921-6c82da00-b2cf-11e9-93b4-6526169dc0a3.png)
![Picture2](https://user-images.githubusercontent.com/53490321/62151938-71e02480-b2cf-11e9-8628-73a8517c563c.png)

Hello,

I am unable to install Buster. I am not familiar with code, but trying to learn. I am running Kali Linux. See pictures for reference to the message I get when I run the python3 setup.py install. Hopefully, you can help me out!

Thank you!

Roger

**Comment by sham00n** [comment]
can you try now with a fresh clone ?

**Comment by OSINT007** [comment]
I just did and gave me same error as in the pictures.

**Comment by sham00n** [comment]
can u tell me what buster -h returns (try copying and pasting the result and use the insert code button please)

**Comment by OSINT007** [comment]
Apologies for not inserting -

It says

Bash: buster: command not found

**Comment by h4rd1k21** [comment]
I am having the same issue. Please help!

**Comment by sham00n** [comment]
this seems to be the same issue as #1 ,try `pip3 install cython`

**Comment by OSINT007** [comment]
I ran it and subsequently got a message that there was no aiohtto-socks
module found. I ran pip3 install aiohttp_socks  and fixed the issue. Now
I’m running the tool.

Thank you!

**Comment by danhmanh** [comment]
I tried `pip3 install cython` and `pip3 install aiohttp_socks`, but its not working.
