### ISSUE TITLE
Issue with lzma

### ISSUE THREAD

**Issue by silverbakk** [sham00n/buster#5]
Hello, after installing this and following the setup, upon running "buster -h" I am given the error...

`  File "/usr/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'`

I have assured pylzma is installed for this python version, so I am if you have a fix for this?

**Comment by sham00n** [comment]
try `sudo apt install liblzma-dev` and recompile python , the problem comes from your python installation.

**Comment by silverbakk** [comment]
Yea I was using 3.6 and instead did a fresh install of 3.7. The setup.py didnt work for me though until I manually added the required libraries listed in the setup.py script. Everything works now! Great tool and thank you!
